#!/bin/bash

set -eu

containers=$(docker-compose ps -q)

if [[ -z "$containers"  ]]
then
    echo "No container is running"
    exit 0
fi

for id in $containers
do
    echo "Checking container $id"
    docker exec -it cassandra-test-cassandra-1-1 nodetool status
done
