version: '3.9'

services:
  cassandra-1:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - "./data/cassandra-1:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster


  cassandra-2:
    image: cassandra:4.0
    ports:
      - 9043:9042
    volumes:
      - "./data/cassandra-2:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_SEEDS=cassandra-1

  cassandra-3:
    image: cassandra:4.0
    ports:
      - 9044:9042
    volumes:
      - "./data/cassandra-3:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
